### ISSUE TITLE
panic: attempt to negate with overflow in `msvc_demangler::ParserState::read_number`

### ISSUE THREAD

**Issue by 0vercl0k** [mstange/msvc-demangler-rust#72]
Hi,

I'm hitting the below panic with the latest version (0.10.0):
```text
> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target\debug\repro_demangler.exe`
thread 'main' panicked at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:824:40:
attempt to negate with overflow
stack backtrace:
   0:     0x7ff64d5cf212 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff64d5dd8fd - core::fmt::rt::Argument::fmt
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\fmt\rt.rs:142
   2:     0x7ff64d5dd8fd - core::fmt::write
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\fmt\mod.rs:1120
   3:     0x7ff64d5cd511 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\io\mod.rs:1846
   4:     0x7ff64d5cf03a - std::sys_common::backtrace::_print
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff64d5cf03a - std::sys_common::backtrace::print
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff64d5d0b99 - std::panicking::default_hook::closure$1
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:272
   7:     0x7ff64d5d0855 - std::panicking::default_hook
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:292
   8:     0x7ff64d5d10b4 - std::panicking::rust_panic_with_hook
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:781
   9:     0x7ff64d5d0f4b - std::panicking::begin_panic_handler::closure$0
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:651
  10:     0x7ff64d5cf8b9 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:171
  11:     0x7ff64d5d0c56 - std::panicking::begin_panic_handler
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:647
  12:     0x7ff64d5e2947 - core::panicking::panic_fmt
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\panicking.rs:72
  13:     0x7ff64d5e2a22 - core::panicking::panic
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\panicking.rs:144
  14:     0x7ff64d5a6760 - msvc_demangler::ParserState::read_number
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:824
  15:     0x7ff64d5ab3c5 - msvc_demangler::ParserState::read_var_type
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:1332
  16:     0x7ff64d5adba8 - msvc_demangler::ParserState::read_params
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:1510
  17:     0x7ff64d5a6cea - msvc_demangler::ParserState::read_template_name
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:879
  18:     0x7ff64d5a7d62 - msvc_demangler::ParserState::read_unqualified_name
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:947
  19:     0x7ff64d5a8356 - msvc_demangler::ParserState::read_name
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:975
  20:     0x7ff64d5aba7c - msvc_demangler::ParserState::read_var_type
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:1397
  21:     0x7ff64d5ad174 - msvc_demangler::ParserState::read_pointee
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:1448
  22:     0x7ff64d5abab2 - msvc_demangler::ParserState::read_var_type
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:1398
  23:     0x7ff64d5adba8 - msvc_demangler::ParserState::read_params
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:1510
  24:     0x7ff64d5a6cea - msvc_demangler::ParserState::read_template_name
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:879
  25:     0x7ff64d5a7d62 - msvc_demangler::ParserState::read_unqualified_name
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:947
  26:     0x7ff64d5a8356 - msvc_demangler::ParserState::read_name
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:975
  27:     0x7ff64d5a2d09 - msvc_demangler::ParserState::parse
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:555
  28:     0x7ff64d5ae456 - msvc_demangler::parse
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:1558
  29:     0x7ff64d5ae2b8 - msvc_demangler::demangle
                               at c:\users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\msvc-demangler-0.10.0\src\lib.rs:1547
  30:     0x7ff64d5a1377 - repro_demangler::main
                               at C:\tmp\repro_demangler\src\main.rs:2
  31:     0x7ff64d5a12cb - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\core\src\ops\function.rs:250
  32:     0x7ff64d5a157e - core::hint::black_box
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\core\src\hint.rs:334
  33:     0x7ff64d5a157e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\std\src\sys_common\backtrace.rs:155
  34:     0x7ff64d5a1071 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\std\src\rt.rs:166
  35:     0x7ff64d5cab72 - std::rt::lang_start_internal::closure$2
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\rt.rs:148
  36:     0x7ff64d5cab72 - std::panicking::try::do_call
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:554
  37:     0x7ff64d5cab72 - std::panicking::try
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:518
  38:     0x7ff64d5cab72 - std::panic::catch_unwind
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panic.rs:142
  39:     0x7ff64d5cab72 - std::rt::lang_start_internal
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\rt.rs:148
  40:     0x7ff64d5a104a - std::rt::lang_start<tuple$<> >
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\std\src\rt.rs:165
  41:     0x7ff64d5a14d9 - main
  42:     0x7ff64d5e1430 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  43:     0x7ff64d5e1430 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  44:     0x7ff83fd7257d - BaseThreadInitThunk
  45:     0x7ff83ff8aa48 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\repro_demangler.exe` (exit code: 101)
```

Here's a repro:
```rust
fn main() {
    let r = msvc_demangler::demangle("??$TypedThrowBadVariantAccess@AEBV?$IdType@VGpuDiskCacheDawnWebGPU@gpu@@H$0?IAAAAAAA@$00$S@base@@@variant_internal@absl@@YAAEBV?$IdType@VGpuDiskCacheDawnWebGPU@gpu@@H$0?IAAAAAAA@$00$S@base@@XZ", msvc_demangler::DemangleFlags::NAME_ONLY);
    println!("{r:?}");
}
```

It's also worth to mention that this mangled symbol comes from a legit PDB; it isn't 'synthetic'.

This is how the Windows debugger seems to demangle the symbol, at least partially: 
- `absl::variant_internal::TypedThrowBadVariantAccess<const ThreadProfilerConfiguration::BrowserProcessConfiguration &> ` 

And this is what `msvc_demangler` returns in `release`:
- `absl::variant_internal::TypedThrowBadVariantAccess<class base::IdType<class gpu::GpuDiskCacheDawnWebGPU,int,-2147483648,1> const &>`

Cheers

**Comment by mstange** [comment]
Thanks for filing! This is definitely worth fixing. Luckily it only panics in debug builds.
I'd be happy to review a fix if you get to it before I do.

**Comment by 0vercl0k** [comment]
It is indeed great that this only happens in debug builds :) Cool, let me
try to come up with something then; I should have time to look at this next
week.

Cheers

**Comment by 0vercl0k** [comment]
OK I took a look at this today and what happens is that `IAAAAAAA` (`b'I' - b'A' = 8`) ends up decoding as `0x8000_0000` and as `?` is present before it, it is trying to negate `0x8000_0000` which overflows.

I sent #74 to address this.

Cheers

**Comment by mstange** [comment]
Fixed by #74. Thanks!

I noticed after merging that the commit message in #74 refers to #17 rather than this issue which is #72.

**Comment by 0vercl0k** [comment]
Yeah ugh, that's my bad - I edited the PR title but I should have done that on the commit. I don't think I can fix that now from my side, but let me know if I can, happy to send an edited PR or something.

Cheers

**Comment by mstange** [comment]
No worries, people will be able to find it if they really want to. I'll do some housekeeping and then release a fixed version.

**Comment by 0vercl0k** [comment]
Cheers Markus, thank you again for authoring and maintaining this project!
